---
label: Product
hide_body: true
fields:
- name: short_name
  type: text
  config:
    required: true
  label: Short Name
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
- name: driveaway_price
  type: number
  label: Driveaway price
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: featured
  type: boolean
  label: Featured
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: available_colours
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: body-paints
  label: Available Colours
pages:
- data/products/ferrari-296-gtb.md
- data/products/maserati-mc20.md
